name: Java CI

on:
  push:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set up JDK 1.21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'adopt'


      - name: Test
        run: gradle test

      - name: Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Gradle Tests
          path: build/reports/tests/test/index.html
          reporter: java-junit
          fail-on-error: true
